// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIKVc-siDJBmseHauc9h1Bd43vxh2ZaZI',
    appId: '1:344330549483:web:9ceb846ea96304069fa6ae',
    messagingSenderId: '344330549483',
    projectId: 'aquaops-e8dd1',
    authDomain: 'aquaops-e8dd1.firebaseapp.com',
    storageBucket: 'aquaops-e8dd1.firebasestorage.app',
    measurementId: 'G-BVYQ42300X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAycNB9kguvmRWPN2YONLhmB6Q9LLZ4H9U',
    appId: '1:344330549483:android:56f97e2338b288569fa6ae',
    messagingSenderId: '344330549483',
    projectId: 'aquaops-e8dd1',
    storageBucket: 'aquaops-e8dd1.firebasestorage.app',
  );
}
